name: Create and Upload Release Zip

on:
  push:
    branches:
      - main  # Change if your default branch is different

permissions:
  contents: write  # Grants permission to create/update releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version and description from commit message
        id: extract_info
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          VERSION=$(echo "$COMMIT_MSG" | grep -oP '^\d+\.\d+\.\d+')
          DESCRIPTION=$(echo "$COMMIT_MSG" | sed -E 's/^[0-9]+\.[0-9]+\.[0-9]+: //')

          echo "Extracted version: '$VERSION'"
          echo "Extracted description: '$DESCRIPTION'"

           echo "::set-output name=version::$VERSION"
          echo "::set-output name=description::$DESCRIPTION"

      - name: Verify version in system.json
        run: |
          FILE_VERSION=$(jq -r .version system.json)
          echo "system.json version: $FILE_VERSION"
          echo "commit version: ${{ steps.extract_info.outputs.version }}"
          if [ "${{ steps.extract_info.outputs.version }}" != "$FILE_VERSION" ]; then
            echo "Version mismatch: Commit message version (${{ steps.extract_info.outputs.version }}) does not match system.json version ($FILE_VERSION)" >&2
            exit 1
          fi

      - name: Create zip file
        run: |
          ZIP_NAME="release-${{ steps.extract_info.outputs.version }}.zip"
          zip -r "$ZIP_NAME" . -x "*.git*"
          echo "zip_name=$ZIP_NAME" >> $GITHUB_ENV

      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: ${{ steps.extract_info.outputs.version }}
          body: ${{ steps.extract_info.outputs.description }}
          draft: false
          prerelease: false
          files: ${{ env.zip_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
